# Generated by Django 4.2.5 on 2023-09-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('image_url', models.CharField(blank=True, default=False, max_length=3000)),
                ('available', models.BooleanField(default=False)),
            ],
        ),
    ]
