# Generated by Django 4.2.5 on 2023-10-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_cart_products_type_alter_products_price_cartitems_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='type',
            field=models.CharField(default='', max_length=200),
        ),
    ]
